### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Junren0716** [Rhyssiyan/goodluck#2]
![屏幕快照 2019-03-15 下午9 52 04](https://user-images.githubusercontent.com/16787999/54435969-a57d4080-476c-11e9-801e-c61808602ac3.png)

**Comment by Rhyssiyan** [comment]
emm... I updated the program recently. Try it again.
And please include your command next time when you report the bug. Thanks.

**Comment by Junren0716** [comment]
Solved, thanks.

**Comment by Junren0716** [comment]
`$ goodluck watch

Traceback (most recent call last):
  File "/root/anaconda3/bin/goodluck", line 222, in <module>
    fire.Fire(runner)
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/root/anaconda3/bin/goodluck", line 172, in watch
    card = check_and_convert_card(card)
  File "/root/anaconda3/bin/goodluck", line 44, in check_and_convert_card
    c = CARD_MAPPING[c]
KeyError: 'TITAN V'
`
